<?php

namespace MappedSuperclassesBundle\Repository;

/**
 * SubSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
